version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    ports:
      - '28306:3306'
    volumes:
      - "mysql_data:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8",
      "--collation-server=utf8_bin"
    ]  
    restart: unless-stopped
    networks:
      monitoring_network:
        ipv4_address: 172.28.0.5

  zabbix_frontend:
    image: zabbix/zabbix-web-nginx-mysql:trunk-ubuntu
    container_name: zabbix_frontend
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    env_file:
      - .env
    environment:
      DB_SERVER_HOST: ${DB_SERVER_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}
      PHP_TZ: ${PHP_TZ}
      TZ: ${TZ}
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      monitoring_network:
        ipv4_address: 172.28.0.10

  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:trunk-ubuntu
    container_name: zabbix-server-mysql
    ports:
      - '10050:10050'
      - '10051:10051'
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    env_file:
      - .env
    environment:
      DB_SERVER_HOST: ${DB_SERVER_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ZBX_ENABLE_SNMP_TRAPS: ${ZBX_ENABLE_SNMP_TRAPS}
      TZ: ${TZ}
    depends_on:
      - mysql      
    restart: unless-stopped
    networks:
      monitoring_network:
        ipv4_address: 172.28.0.15

#  zabbix-agent:
#    image: zabbix/zabbix-agent:trunk-ubuntu
#    container_name: zabbix-agent
#    ports:
#      - '10050:10050'
#    volumes:
#      - "/etc/localtime:/etc/localtime:ro"
#      - "/etc/timezone:/etc/timezone:ro"
#    env_file:
#      - .env
#    environment:
#      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}
#      TZ: ${TZ}
#    restart: unless-stopped
#    networks:
#      monitoring_network:
#        ipv4_address: 172.28.0.20

  zabbix-snmptraps:
    image: zabbix/zabbix-agent:trunk-ubuntu
    container_name: zabbix-snmptraps
    ports:
      - '162:1162/udp'
    volumes:
      - "./zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw"
      - "./zabbix/mibs:/usr/share/snmp/mibs:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    env_file:
      - .env
    environment:
      TZ: ${TZ}
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      monitoring_network:
        ipv4_address: 172.28.0.25       

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
      - "23000:3000"
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    depends_on:
      - mysql 
      - zabbix-server-mysql    
    restart: unless-stopped
    networks:
      monitoring_network:
        ipv4_address: 172.28.0.30

networks:
  monitoring_network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.28.0.0/16

volumes:
  mysql_data:
  grafana_data: