version: "3.8"

volumes:
  mysql_data:
  grafana_data:

networks:
  monitoring_network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.28.0.0/16

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    ports:
      - '28306:3306'
    volumes:
      - "mysql_data:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${TZ}
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--character-set-server=utf8",
      "--collation-server=utf8_bin"
    ]  
    restart: unless-stopped
    networks:
      monitoring_network:
        ipv4_address: 172.28.0.5

  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-mysql
    container_name: zabbix-frontend
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    env_file:
      - .env
    environment:
      DB_SERVER_HOST: ${DB_SERVER_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}
      PHP_TZ: ${PHP_TZ}
      TZ: ${TZ}
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      monitoring_network:
        ipv4_address: 172.28.0.10

  zabbix-server:
    image: zabbix/zabbix-server-mysql
    container_name: zabbix-server
    ports:
      - '10050:10050'
      - '10051:10051'
    volumes:
      - "./zabbix/zabbix-server/alertscripts:/usr/lib/zabbix/alertscripts"
      - "./zabbix/zabbix-server/externalscripts:/usr/lib/zabbix/externalscripts"
      - "./zabbix/zabbix-server/modules:/var/lib/zabbix/modules"
      - "./zabbix/zabbix-server/enc:/var/lib/zabbix/enc"
      - "./zabbix/zabbix-server/snmptraps:/var/lib/zabbix/snmptraps"
      - "./zabbix/zabbix-server/mibs:/var/lib/zabbix/mibs"
      - "./zabbix/zabbix-server/export:/var/lib/zabbix/export"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    env_file:
      - .env
    environment:
      DB_SERVER_HOST: ${DB_SERVER_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      ZBX_ENABLE_SNMP_TRAPS: ${ZBX_ENABLE_SNMP_TRAPS}
      TZ: ${TZ}
    depends_on:
      - mysql      
    restart: unless-stopped
    networks:
      monitoring_network:
        ipv4_address: 172.28.0.15

#  zabbix-agent:
#    image: zabbix/zabbix-agent
#    container_name: zabbix-agent
#    ports:
#      - '10050:10050'
#    volumes:
#      - "/etc/localtime:/etc/localtime:ro"
#      - "/etc/timezone:/etc/timezone:ro"
#    env_file:
#      - .env
#    environment:
#      ZBX_SERVER_HOST: ${ZBX_SERVER_HOST}
#      TZ: ${TZ}
#    restart: unless-stopped
#    networks:
#      monitoring_network:
#        ipv4_address: 172.28.0.20

  zabbix-snmptraps:
    image: zabbix/zabbix-agent
    container_name: zabbix-snmptraps
    ports:
      - '162:1162/udp'
    volumes:
      - "./zabbix/zabbix-snmptraps/snmptraps:/var/lib/zabbix/snmptraps"
      - "./zabbix/zabbix-snmptraps/mibs:/var/lib/zabbix/mibs"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    env_file:
      - .env
    environment:
      TZ: ${TZ}
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      monitoring_network:
        ipv4_address: 172.28.0.25       

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    ports:
      - "23000:3000"
    volumes:
      - "grafana_data:/var/lib/grafana"
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    depends_on:
      - mysql 
      - zabbix-server-mysql    
    restart: unless-stopped
    networks:
      monitoring_network:
        ipv4_address: 172.28.0.30